### ISSUE TITLE
odw database structure is missing

### ISSUE THREAD

**Issue by ahmedsamer** [AAbouZaid/Opsview-ODW-Legacy-Support#2]
Ahmed,
  Please don't forget to upload odw_database_structure.sql

Regards

**Comment by aabouzaid** [comment]
Just pushed [229ba61](https://github.com/AAbouZaid/Opsview-ODW-Legacy-Support/commit/5b04d90584a91daf7d134ae8860b5b780437fb95) :-D
Thanks Samer :D
